default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost
  port: 3306


development:
  <<: *default
  database: futuro5_development

test:
  <<: *default
  database: futuro5_test

production:
  <<: *default
  database: futuro5_production
  username: futuro5
  password: <%= ENV['FUTURO5_DATABASE_PASSWORD'] %>
